spring.application.name=boot
server.port=8080


#DB
#bootdb / bootUser / mysql
spring.datasource.driver-class-name=net.sf.log4jdbc.sql.jdbcapi.DriverSpy
spring.datasource.url=jdbc:log4jdbc:mysql://localhost:3306/bootdb?serverTimezone=Asia/Seoul
spring.datasource.username=bootUser
spring.datasource.password=mysql


#git설정


#jpa 설정
spring.jpa.database=mysql
#ddl-auto 원래는 none이 디폴트임.  ㅈ대로 수정하지 말라는 뜻인가벼
#create - 테이블 자동생성 기존테이블 있으면 삭제하고 재생성
#create drop  테이블 자동생성 (단 애플리케이션 종료시 테이블 삭제   지속적인 테이블의 리셋    사실상 안쓰는듯
#update    create와 생성은 동일한데 기존 테이블이 있으면 추가되는 사항만 변경해줌.
#validate  생성수정안함.   정상 매핑 여부만 검사하는 수쥰.
#일반적으로 개발단계에서는 update를 줌.   그리고 테스트를 할때 잘 되면 update&validate  배포운영까지오면 none

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true







