log4jdbc.spylogdelegator.name=net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
#sql 문장내에 존재하는 불필요한 공백을 자동으로 제거하고 출력해달라는 구문.
#쿼리자체가 쓸데없이 길어지는걸 막고 로그를 줄이는 목적임.  그리고 줄여지면 한눈에 쿼리 읽기 쉬워짐.ㅋㅋ

log4jdbc.trim.sql.extrablanklines=true

#콘솔에 출력할 sql 한줄 최대 글자수
log4jdbc.maxlinelength=500


